# Site settings
title: Event Horizon
SEOTitle: 杨一江的博客 | Yi-Jiang Yang Blog
header-img: img/home-bg.jpg
email: swimiltylers@gmail.com
description: "学习分布式算法 | 杨一江，Food Lover，Undergraduate of NJU | 这里是 @swimiltylers 的个人博客，与你一起发现更大的世界"
keyword: "杨一江, Swimiltylers, yangyj, @swimiltylers, 杨一江的博客, Yi-Jiang Yang Blog, 博客, 个人网站, 分布式算法, Distributed Algorithm, 形式语义, Coq"
url: "https://swimiltylers.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     swimiltylers
zhihu_username:     yang-yi-jiang-40
github_username:    swimiltylers
twitter_username:   swimiltylers
facebook_username:  swimiltylers
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: swimiltylers

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-125889251-1'            # Format: UA-xxxxxx-xx
ga_domain: swimiltylers.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Live long and prosper<br>生生不息，繁荣昌盛"
sidebar-avatar: /img/avatar-yangyj-sidebar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Eillon Ye",
        href: "https://eillon.github.io/"
    }
]
